return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "cpp",
      "dart",
      "dockerfile",
      "go",
      "gomod",
      "html",
      "java",
      "javascript",
      "json",
      "json5",
      "kotlin",
      "latex",
      "lua",
      "markdown",
      "markdown_inline",
      "nix",
      "nushell",
      "python",
      "query",
      "regex",
      "rust",
      "sql",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
