"""Pure mapping helpers: domain models -> swaync wire formats (JSON/CSS).

No I/O here, so these are trivially unit-testable. The adapter calls them and
writes the result to disk.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence

from domain.models import (
    Button,
    CssComponent,
    CssDeclaration,
    StyleSheet,
    SwayncConfig,
    Widget,
)

# ── JSON (config.json) ──────────────────────────────────────────────────────


def button_to_dict(button: Button) -> dict[str, object]:
    payload: dict[str, object] = {"label": button.label, "type": button.kind.value}
    if button.kind.value == "toggle":
        payload["active"] = button.active
    payload["command"] = button.command
    if button.update_command is not None:
        payload["update-command"] = button.update_command
    return payload


def _option_to_value(value: object) -> object:
    if isinstance(value, Button):
        return button_to_dict(value)
    if isinstance(value, Sequence) and not isinstance(value, str):
        return [_option_to_value(item) for item in value]
    return value


def widget_options(widget: Widget) -> dict[str, object]:
    return {key: _option_to_value(value) for key, value in widget.options.items()}


def widget_to_dict(widget: Widget) -> dict[str, object]:
    return widget_options(widget)


def config_to_dict(config: SwayncConfig) -> dict[str, object]:
    behavior = config.behavior
    layout = config.layout
    margins = layout.margins
    return {
        "$schema": config.schema,
        "positionX": config.position.x,
        "positionY": config.position.y,
        "layer": config.layer.layer,
        "control-center-layer": config.layer.control_center_layer,
        "layer-shell": behavior.layer_shell,
        "layer-shell-cover-screen": behavior.layer_shell_cover_screen,
        "cssPriority": behavior.css_priority,
        "control-center-margin-top": margins.top,
        "control-center-margin-bottom": margins.bottom,
        "control-center-margin-right": margins.right,
        "control-center-margin-left": margins.left,
        "notification-window-width": layout.notification_width,
        "control-center-width": layout.control_center_width,
        "control-center-height": layout.control_center_height,
        "fit-to-screen": layout.fit_to_screen,
        "notification-2fa-action": behavior.notification_2fa_action,
        "notification-inline-replies": behavior.inline_replies,
        "notification-grouping": behavior.grouping,
        "relative-timestamps": behavior.relative_timestamps,
        "image-visibility": behavior.image_visibility.value,
        "keyboard-shortcuts": behavior.keyboard_shortcuts,
        "transition-time": behavior.transition_time_ms,
        "timeout": behavior.timeout,
        "timeout-low": behavior.timeout_low,
        "timeout-critical": behavior.timeout_critical,
        "hide-on-clear": behavior.hide_on_clear,
        "hide-on-action": behavior.hide_on_action,
        "text-empty": behavior.text_empty,
        "script-fail-notify": behavior.script_fail_notify,
        "widgets": [widget.key() for widget in config.widgets],
        "widget-config": {widget.key(): widget_to_dict(widget) for widget in config.widgets},
    }


def config_to_json(config: SwayncConfig) -> str:
    return json.dumps(config_to_dict(config), indent=2, ensure_ascii=False) + "\n"


# ── CSS (style.css) ─────────────────────────────────────────────────────────


def declaration_to_css(declaration: CssDeclaration) -> str:
    return f"  {declaration.prop}: {declaration.value};"


def component_to_css(component: CssComponent) -> str:
    selector = ",\n".join(component.selectors)
    body = "\n".join(declaration_to_css(item) for item in component.declarations)
    return f"{selector} {{\n{body}\n}}"


def stylesheet_to_css(sheet: StyleSheet) -> str:
    lines = [
        "/* SwayNC — Catppuccin Mocha with the waybar pill language.",
        " * GENERATED by scripts/main.py — edit domain/workflows/theme.py instead.",
        " */",
        "",
    ]

    for color in sheet.palette:
        lines.append(f"@define-color {color.name} {color.literal()};")
    lines.append("")

    if sheet.tokens:
        lines.append(":root {")
        lines.extend(declaration_to_css(item) for item in sheet.tokens)
        lines.append("}")
        lines.append("")

    section: str | None = None
    for component in sheet.components:
        if component.section and component.section != section:
            section = component.section
            lines.append(f"/* ── {section} ── */")
            lines.append("")
        lines.append(component_to_css(component))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def describe(config: SwayncConfig) -> Mapping[str, object]:
    """Small summary for logging (no I/O)."""
    return {
        "widgets": len(config.widgets),
        "keys": config.widget_keys(),
    }
