from typing import Protocol


class Logger(Protocol):
    def info(self, message: str) -> None: ...

    def error(self, message: str) -> None: ...

    def success(self, message: str) -> None: ...

    def warning(self, message: str) -> None: ...

    def dry_run(self, message: str) -> None: ...
